### ISSUE TITLE
Table view for browsing (besides List and Grid)

### ISSUE THREAD

**Issue by DBinaghi** [omeka/theme-foundation#33]
Besides List and Grid view, a Table view (with relative toggle button) would be useful to add to Browse pages. 
Possibly, with a chance to choose which columns to show and in which order (and additional option to toggle Column Headers); see GSoules' AvantSearch plugin page to have visual examples.

**Comment by DBinaghi** [comment]
These are just a couple of suggestions:

![image](https://user-images.githubusercontent.com/39097246/112521292-a3f3a380-8d9c-11eb-88c1-716199837b7d.png)

![image](https://user-images.githubusercontent.com/39097246/112521375-ba99fa80-8d9c-11eb-86db-31e4973a775d.png)

**Comment by kimisgold** [comment]
Since this issue was filed, the [FacetedBrowse](https://github.com/omeka-s-modules/FacetedBrowse) module has been released, and features a table with customizable columns. Using that for a project's item browse would be my recommendation for a table layout option.
