### ISSUE TITLE
gulp-sass 5 does not have a default Sass compiler; please set one yourself. when running npm start

### ISSUE THREAD

**Issue by Gilles-Lengy** [omeka/theme-foundation#56]
What I did:

Copy foundation and rename the folder.
Update theme.ini
Change the theme.jpg
run npm install and npm audit fix
run npm start, I had an error.
I changed the gulpfile.js

https://github.com/Gilles-Lengy/omeka-theme-flex-classic/commit/23c90db6ae90be0a72b22d3d9b947880636a4b69

run npm install sass gulp-sass --save-dev

After that I could run npm start without errors.

You can see the detail here:

https://github.com/Gilles-Lengy/omeka-theme-flex-classic/issues/1
https://github.com/Gilles-Lengy/omeka-theme-flex-classic/issues/2

**Comment by kimisgold** [comment]
Thank you for reporting this. This issue was addressed in https://github.com/omeka/theme-foundation/commit/013211c744a983f8d6156d39fe54074ca6f9c946 and my apologies as I forgot to reply back here.
